### PR TITLE
Format company contacts

### LINKED ISSUE #12: Format address in table
Put addresses into a table to improve readability
screen shot 2015-02-10 at 9 22 18 am

### LINKED ISSUE #16: Making fields sortable
Add functionality to sort company and contract values alphabetically screen shot 2015-02-18 at 10 48 58 pm

### LINKED ISSUE #19: Add pagination for search results

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
+ Reformat addresses
+ Add pagination to lengthy search results
+ Make search fields sortable by clicking on table headers

### Issues
+ Fixes #12 (Format addresses in a table)
+ Fixes #16 (Make search fields sortable)
+ Fixes #19 (Add pagination for search results)

### Screencap
wexplore-search

### CODE REVIEW

**Comment by bsmithgall** [comment]
There is a weird bug where you can end up with a bunch of duplicate contact info, looking into it now

**Comment by bsmithgall** [comment]
Turns out it's not a bug, that particular contact just has three distinct fax numbers. Fixing it to only look at the columns we are pulling instead of everything

**Comment by shellicious** [comment]
looks good to me!

**Comment by hamhands** [comment]
Woot sortable things LGTM :+1:

**Pull request merged**
