### PR TITLE
Soon to expire view

### PR DESCRIPTION
**Pull request by bsmithgall**
### What Changed
+ Added view with contracts organized by expiration date
+ Added custom text based on expiration date

### Issues
+ #17 add view with soon to expire contracts

### Screencap
template-maker-current-flow

### CODE REVIEW

**Comment by hamhands** [comment]
As we add new features it might be good to highlight them a bit more on the landing page. Something like "**New: Find contracts about to expire**" maybe in a h3?

**Comment by bsmithgall** [comment]
that looks kinda silly tbh...

screen shot 2015-04-01 at 10 22 53 am

**Comment by hamhands** [comment]
Yes, that does look silly. I'm thinking something like the protip at the bottom of this page: 
screen shot 2015-04-01 at 10 23 50 am

**Comment by shellicious** [comment]
I'd forgo the sentence on the front page, and change the menu on the left hand side of the page in the search results view:
- remove Explore and About links
- Insert a heading that says: "Filter by"
- Have checkboxes for: "Expiring soon", and "Expired"

Like FBOpen: 
screen shot 2015-04-01 at 10 26 12 am

**Comment by bsmithgall** [comment]
@shellicious So just the front page the way it is?

**Comment by bsmithgall** [comment]
Also, these are different views entirely; should they be merged into one?

**Comment by bsmithgall** [comment]
Updated:
template-maker-current-flow

**Comment by bsmithgall** [comment]
@shellicious we should decide if we are wontfixing this

**Comment by bsmithgall** [comment]
Can you bring it up in your meeting with Riley?

**Comment by bsmithgall** [comment]
Based on feedback, we're going to close and WONTFIX this.

**Pull request closed without merging**
