### PR TITLE
Add advanced search

### PR DESCRIPTION
**Pull request by bsmithgall**
NOTE: Dramatic database changes required before deployment is possible!

### What Changed
+ Updated database and models to conform to new UUID-based structure (change due to de-dupe in the extraction tool. See [here]() for more details).
+ Search now covers controller numbers (exactly matches) and items entered via the form on the company page.

### Issues
#10: Have search include items that have been bought previously
#11: Build out an advanced search that includes additional fields

### Screenshots
Search by controller number:
Search by controller number
New copy on home page:
screen shot 2015-02-11 at 1 54 01 pm

### CODE REVIEW

**Comment by hamhands** [comment]
I like adding the copy to the main page, but I think it's too prominent for my eyes. Wonder what @shellicious has to say about it.

**Comment by bsmithgall** [comment]
Bumping this @shellicious @hamhands

**Comment by shellicious** [comment]
@bsmithgall the box / green button is the thing we want people to do, but it's the smallest thing on the page. Make box + green button of blurb under Wexplorer logo. Make type in the box (grey text) and button the same size as the type below it.

**Comment by bsmithgall** [comment]
How's this?

screen shot 2015-02-18 at 8 35 19 pm

**Pull request merged**
